### ISSUE TITLE
Create the views

### ISSUE THREAD

**Issue by davesnx** [sanack/atom-jq#1]
- Understand how views work on atom: https://atom.io/docs/api/v1.8.0/ViewRegistry and https://atom.io/docs/api/v1.8.0/Workspace
- View of the input
- View of the right modal
- View of the errors

**Comment by davesnx** [comment]
I get a lot of troubles to use [atom-space-pen-views](https://github.com/atom/atom-space-pen-views) for creating the views on atom.
- First no `jquery` founded.
- I can't `apm install`
- If I import 'jquery' directly fails with some random apply...

I solve it using react for the view, I want to test how much cost to load `react` and `react-dom` for just a small view system, in case that is too much I will use some react-alternative. (https://github.com/sanack/atom-jq/commit/d2774837c090347587ee37c5328fec9bf9eb6fa4)

**Comment by davesnx** [comment]
I just push direclty to master, because I don't have any funcionality, it's just a experiment as soon as I get it work I will block master and create PR, and as soon as I publish it we can do the same as the [node-jq](https://github.com/sanack/node-jq/) repo.

@mackermans

**Comment by mackermans** [comment]
Let's do some pp later so i can jump into this too

**Comment by davesnx** [comment]
https://github.com/sanack/atom-jq/pull/10/
