### ISSUE TITLE
Cannot install via apm

### ISSUE THREAD

**Issue by antono** [sanack/atom-jq#50]
Unable to download https://www.atom.io/api/packages/atom-jq/versions/0.6.1/tarball: 404

**Comment by antono** [comment]
And version 0.7.0 seems not published.

**Comment by davesnx** [comment]
Hello @antono 

We are having issues with the **Continuous Integration** of atom-jq.
Last time that I touched it was frustrating, let me check it once more.

Thanks for raising the issue!

**Comment by mamyn0va** [comment]
Any news? Problem is still there.

**Comment by mackermans** [comment]
@borisjamot I just published version `0.7.0` to `apm`, so you should be able to get that version now. Let me know if it works.

@davesnx To prevent this from happening in the future, we need to adjust our `semantic-release`  script to support the `apm publish` flow, so that it's all automated.

**Comment by mamyn0va** [comment]
Hi @mackermans, it sounds better now as I'm able to install the package @0.7.0, but now I get an error `Unknown path` when trying to run jq on a JSON file.

**Comment by davesnx** [comment]
That's the issue that I was worried @mackermans.

We update to the new node-jq and it fails :(

**Comment by davesnx** [comment]
Hello @borisjamot,

I just tried and seems that works perfectly. Our tests are passing. Can you provide more info about your error. Thanks!

**Comment by mamyn0va** [comment]
I have the following JSON (LF, UTF8):

```json
{
    "test":"toto"
}
```

When I type keys or .test in the jq input area, I get the following error message in the top-right popup:

"Le chemin d'acc�s sp�cifi� est introuvable."
