### ISSUE TITLE
Allow running on files that don't end in .json

### ISSUE THREAD

**Issue by cdzombak** [sanack/atom-jq#51]
Right now node-jq [always verifies](https://github.com/sanack/node-jq/blob/master/src/options.js#L12) that a given file path ends in `.json`. I sometimes work with temporary JSON files, though, that don't have any extension.

This results in an error, "Not a .json file," when I try to use atom-jq, even though working with these files with `jq` on the command line works fine.

It would be nice to be able to use atom-jq with JSON files that don't have extensions. I imagine this would require some changes to both atom-jq and node-jq.

**Comment by davesnx** [comment]
Hey @cdzombak,

Thanks for open the issue. I will take a look, at the start that was a "sanity-check". Let's see if still make sense, Thanks!

**Comment by cdzombak** [comment]
A sanity check probably still makes sense (you wouldn't want to run `jq` on a `.csv` file), but temporary files often have no extension. Perhaps the sanity check could just be expanded to accept such files in addition to `.json` files.
