### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by phinehas** [sanack/atom-jq#84]
Hi, i installed atom-jq from atom packages. Then i opened jq in atom editor to enter a jq filter command. And then when i clicked on [run filter] button i keep having this error [the system cannot find the path specified].

Can you help me resolve this please?

**Comment by davesnx** [comment]
Sure, could you specify which version do you have installed?

**Comment by phinehas** [comment]
The atom x64 windows zip 1.57.0 x64. And the atom-jq version is 0.7.0

**Comment by davesnx** [comment]
Do you have jq installed globally in your system?

**Comment by phinehas** [comment]
i don't know. i installed jq off Atom packages. How can i know if i have it globally installed?

**Comment by davesnx** [comment]
If you are running MacOS or Linux, run `which jq` in the terminal.

**Comment by phinehas** [comment]
i am running Windows 10. i ran the command in my terminal and it shown me the path where jq is installed with an execute into the directory. Do you think this might be the cause? Because it is not pointing to the atom-jq installed into .atom directory

**Comment by phinehas** [comment]
i decided to use jq in command line directly. Thx for your time.

**Comment by davesnx** [comment]
Sorry for not being helpful here, this package hasn't been maintained either used in a while.
